### ISSUE TITLE
LLVM ERROR: Symbol not found: __svml_pow2_ha

### ISSUE THREAD

**Issue by protector131090** [numz/sd-wav2lip-uhq#10]
Can someone help with this error?

**Comment by numz** [comment]
hi,

wow strange one ....
Can you send me the full context of your issue please?

**Comment by protector131090** [comment]
> 

that is all. i try launching and it says "Extracting audio" than next line the erorr. And crashes SD altogether. Never seen this erorr before.

**Comment by numz** [comment]
can you make a print screen of the "cmd" window please?

**Comment by protector131090** [comment]
> can you make a print screen of the "cmd" window please?

https://ibb.co/TLSrVQm [https://ibb.co/TLSrVQm](url)

**Comment by numz** [comment]
thanks,
when did you install sd-wa2lip-uhq, please?

**Comment by protector131090** [comment]
> thanks, when did you install sd-wa2lip-uhq, please?

about an hour ago

**Comment by numz** [comment]
ok,
please, can you tell me the librosa version in the requirements.txt?
in extensions\sd-wav2lip-uhq\requirements.txt

**Comment by protector131090** [comment]
> ok, please, can you tell me the librosa version in the requirements.txt? in extensions\sd-wav2lip-uhq\requirements.txt

imutils
dlib-bin
numpy
opencv-python
scipy
requests
pillow
librosa==0.8.0
opencv-contrib-python
tqdm
numba
imutils
imageio_ffmpeg

**Comment by numz** [comment]
thanks, 
in the folder "extensions\sd-wav2lip-uhq\scripts\wav2lip\temp" do you see a "temp.wav" that corresponding to your audio?

**Comment by protector131090** [comment]
> thanks, in the folder "extensions\sd-wav2lip-uhq\scripts\wav2lip\temp" do you see a "temp.wav" that corresponding to your audio?

yes

**Comment by numz** [comment]
can you test with another audio please?

**Comment by protector131090** [comment]
> can you test with another audio please?

Same error. 4 different audio files

**Comment by numz** [comment]
ok, i make an update, can you update sd-wav2lip-uhq and tell me if it fix?

**Comment by protector131090** [comment]
> 

Using cuda for inference.
Reading video frames...
Number of frames available for inference: 24
LLVM ERROR: Symbol not found: __svml_pow2_ha

**Comment by numz** [comment]
on the web, what i understand is sometimes this error come from numpy, so perhaps if you uninstall and reinstall numpy
i use numpy==1.23.5

**Comment by protector131090** [comment]
> on the web, what i understand is sometimes this error come from numpy, so perhaps if you uninstall and reinstall numpy i use numpy==1.23.5

didnt help.

**Comment by numz** [comment]
I'm sorry, i'm eally trying to help you but this error is strange... did you have other app that having this kind of issue ?

**Comment by protector131090** [comment]
> I'm sorry, i'm really trying to help you but this error is strange... did you have other app that having this kind of issue ?

nope. never seen with any python app

**Comment by numz** [comment]
Hi,
Im closing this issue, too low level error..
Sorry

**Comment by numz** [comment]
just for test, 
- can you write this line in your webui-user.bat and restart webui please:

`
set NUMBA_DISABLE_INTEL_SVML=1
`

**Comment by numz** [comment]
Read this, it can help :) : 
https://github.com/numz/sd-wav2lip-uhq/issues/24
