### ISSUE TITLE
So Far Not So Good

### ISSUE THREAD

**Issue by AIMusicExperiment** [numz/sd-wav2lip-uhq#11]
Hi, I'm a content creator on YouTube and I was really excited to try out your new extension so I could make a video about it. . . Well in short, I can't get it to work so it would not be a very good video. . . Seriously though this is to be expected since you just released it. Anyway, when I attempt to generate an output I get the following console error. A1111 is up to date, as are all my dependencies. I have downloaded the appropriate models and placed them in the correcto folders. Do you have any idea what I'm doing wrong, or is this in fact a problem with you extension? Thanks!  
![Wav2Lip](https://github.com/numz/sd-wav2lip-uhq/assets/133187055/68c55ad1-a680-4eed-a311-2c3619bf2b3f)

**Comment by numz** [comment]
Hi,
Sorry about that 

it seems the file : 
"c:\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\face_detection\detection\sfd\s3fd.pth" does not exist, so it try to download one on the net ...

are you sure that you place this file in the good folder?

let me know :)

**Comment by AIMusicExperiment** [comment]
Well it "sort of" existed. the downloaded file was named s3fd-619a316812.pth, so I renamed it to s3fd.pth and it seems to be working now.  

Oh BTW the resize slider in your GUI isn't working. . .

Thanks for your help and your quick attention to my issue.

**Comment by numz** [comment]
True for the slider, it doesn't work as expected...

can you tell me what is your youtube channel? i'll follow for see results :)
Thanks for report and see you :)

**Comment by AIMusicExperiment** [comment]
But wait, there's more. . .It failed again while it was generating, different thing this time. . . Hopefully we can get this sorted out. 

https://www.youtube.com/channel/UCypaKOXWzzTxDvr3jWlfD6g I have been a huge fan of SadTalker, and I intend to compare Wav2Lip with Sad Talker.  Hopefully I can get this working so that I can do so. Here is an earlier video that I did about SadTalker, and I actually mentioned the early work on Wav2Lip in the video as a foundation for SadTalker.  
![Wav2Lip](https://github.com/numz/sd-wav2lip-uhq/assets/133187055/f36b5927-0d88-47bd-8afa-0b1c541cd65c)

**Comment by numz** [comment]
please can you update sd-wav2lip-uhq and restart the UI?
please, let me know if this error come again

**Comment by AIMusicExperiment** [comment]
Using the current commit, 6967d1a4 in A1111, and I did a git pull on the folder and it said it was up to date. It gave me the same error after it generated the first frame. Seems like it is having trouble saving the image. . .

**Comment by numz** [comment]
And did you restart the UI?
it's important, because sometime it keep parameters in memory...
I ever had the same error on different projet, like deforum and my only solution was to completly restart UI ... i'm not sure it's especially due to wav2lip..
Let me know

**Comment by AIMusicExperiment** [comment]
Yep, restarted the Server and the ui

**Comment by numz** [comment]
ok and did you do something else in the UI before play with wav2lip?

**Comment by AIMusicExperiment** [comment]
Yes, I made a video on SadTalker, But I reloaded after that

**Comment by numz** [comment]
that come from the option "grid_save" in options , let me check something.... i'm back quickly

**Comment by numz** [comment]
just for test if that came from here, can you go to :
Settings => Saving images/grids => and uncheck "Always save all generated image grids" please?

and retry 

Sorry about those inconvenient...

**Comment by AIMusicExperiment** [comment]
That seems to have solved it, at least as far as we can tell, but it still has lots of frames to process. I will let you know later. . .

**Comment by numz** [comment]
Ok i see...

do you have the same options in the "paths for savings settings"?
![ssss](https://github.com/numz/sd-wav2lip-uhq/assets/800903/677460bc-558d-480c-b8bc-56a5f4d36837)

**Comment by AIMusicExperiment** [comment]
Nope, I generate tons of images and they all go to a similar directory structure on a different drive. If I used my main drive it would be full in a week HaHA

**Comment by AIMusicExperiment** [comment]
I just looked and the images are being stored in the correct directories within the sd-wav2lip-uhq folder. I'm guessing that this will all work out!

**Comment by numz** [comment]
ok i find a way to ignore this issue, you can re-check "Always save all generated image grids" 
and after updating wav2lip-uhq the issue will not appear

**Comment by AIMusicExperiment** [comment]
Well I've got good news and bad news for you:
It generated a video, and the lip syncing seems to be working well, but it attached themask to the frame and rendered them together. (see picture) github won't let me upload the video because it is too large, but the video has both the mainframe and the mask side by side. 

Kind of useless if you ask me. . . 

Hope that you can get this fixed.
  
![output_00000](https://github.com/numz/sd-wav2lip-uhq/assets/133187055/8453e6cb-73e1-4e5a-b9f8-eccf7be0fc8d)

**Comment by AIMusicExperiment** [comment]
I went ahead and updated to the new commit that you wrote and reclicked the save grid thing. I'm regenerating this and it looks like it is going to work! I will let you know in the morning.

**Comment by numz** [comment]
Ahhhh cool !!
Let me know :)

**Comment by AIMusicExperiment** [comment]
Yes, that solved the problem.  Now I can get down to work! Thanks again for all your help.

**Comment by numz** [comment]
Perfect !! thank you too for your time !!
I close the issue :)
