### ISSUE TITLE
Who needs high-quality lip sync - contact me!

### ISSUE THREAD

**Issue by ghost** [numz/sd-wav2lip-uhq#118]
I can do lip sync for any character. I reduced the quality to 10 MB in order to upload video. If you are interested, write to me in telegram: The_best_result

https://github.com/numz/sd-wav2lip-uhq/assets/152233811/46a819be-822c-4975-9b36-a1f66774acb1

https://github.com/numz/sd-wav2lip-uhq/assets/152233811/d301efc3-4194-402a-bec4-2d9a058c1ae1

https://github.com/numz/sd-wav2lip-uhq/assets/152233811/fb614449-e3a2-4958-85ba-85ecf0c9fee1

**Comment by numz** [comment]
thanks to leave please
