### ISSUE TITLE
Output video not compleat the talking

### ISSUE THREAD

**Issue by ShmuelRonen** [numz/sd-wav2lip-uhq#12]
Hello... 
Thanks for your adaptation of Wav2LIp for Automatic1111 !!

I encountered such a problem. Creating the low resolution video was successful. But the HD process stopped after 279 frames as if the movie was finished.

Processing frame: 265 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 266 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.62it/s]
Processing frame: 267 of 1133 -- 44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 268 of 1133 -- 44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 269 of 1133 -- 44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.64it/s]
Processing frame: 270 of 1133 -- 44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.66it/s]
Processing frame: 271 of 1133 -- 44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 272 of 1133 -- 44s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.66it/s]
Processing frame: 273 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 274 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.63it/s]
Processing frame: 275 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 276 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.64it/s]
Processing frame: 277 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 278 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 279 of 1133 -- 43s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 280 of 1133 -- 43s/it]
[INFO] Create Video output!
[INFO] Extract Audio from input!
[INFO] Add Audio to Video!
[INFO] Done! file save in output/video_output.mp4

https://github.com/numz/sd-wav2lip-uhq/assets/80190186/50e83be6-6dcd-48e9-96e4-ad04fe6dae0e

https://github.com/numz/sd-wav2lip-uhq/assets/80190186/76615c2d-49e9-45c3-ae1d-55b751281797

**Comment by ShmuelRonen** [comment]
I have now tried again and got the same results:

Processing frame: 275 of 1133 -- 42s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 276 of 1133 -- 41s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.62it/s]
Processing frame: 277 of 1133 -- 42s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.63it/s]
Processing frame: 278 of 1133 -- 42s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.62it/s]
Processing frame: 279 of 1133 -- 42s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.65it/s]
Processing frame: 280 of 1133 -- 42s/it]
[INFO] Create Video output!
[INFO] Extract Audio from input!
[INFO] Add Audio to Video!
[INFO] Done! file save in output/video_output.mp4

**Comment by ShmuelRonen** [comment]
This is the video source:


https://github.com/numz/sd-wav2lip-uhq/assets/80190186/0141c656-aead-4175-9a94-ee4b15a54e75

**Comment by ShmuelRonen** [comment]
> Hi, i'll try to quickly fix it.
> 
> Sorry about that..
> 
> Edit: If you need to quick fix without wait my fix, you can use a video editor and repeat 5 times your original video and use it as input in wav2lip uhq ... i know it's not what you expect but i don't have access to my pc right now...

Thanks!

**Comment by ShmuelRonen** [comment]
> Hi, i'll try to quickly fix it.
> 
> Sorry about that..
> 
> Edit: If you need to quick fix without wait my fix, you can use a video editor and repeat 5 times your original video and use it as input in wav2lip uhq ... i know it's not what you expect but i don't have access to my pc right now...

Wav2lip has a problem with source video files that are over 30 seconds long. So I prefer to wait for you to fix the problem. Because using video source files longer than 30 seconds created problems for me.

**Comment by ShmuelRonen** [comment]
Are you there?

**Comment by numz** [comment]
Hi,
Apologies for the delay, I was on holiday.
I've made the necessary fix. Please update the sd-wav2lip-uhq and let me know how it goes. :)

**Comment by numz** [comment]
I think it's Ok, I close this issue, let me know if you think I have to reopen

Regards

**Comment by ShmuelRonen** [comment]
Thanks!!! I check it today and it's OK now. 
The process is very slow compared to the wav2lip GFPGAN that I use for my productions.

**Comment by numz** [comment]
ok cool, 

I see your facebook, i have let you a comment on your last video for know if you used sd-wav2lip-uhq or an other tool :)

Let me know :)

regards

**Comment by ShmuelRonen** [comment]
From my test GFPGAN is almost 2 times faster in processing the resolution increase.

**Comment by numz** [comment]
I don't say it in README.md but I use the default enhancer which is CodeFormer, but in Automatic1111=>Settings=>Face Restoration you can choose between CodeFormer and GFPGAN, if you can, let's test and tell me if you found any difference :), I'll test too

Regards
