### ISSUE TITLE
The system cannot find the path specified 

### ISSUE THREAD

**Issue by JekillHY** [numz/sd-wav2lip-uhq#14]
Hi!
Trying to install this extension. But after installing and restarting the UI an error is thrown. 
I am using the portable build [A1111 by Xpuct](https://github.com/serpotapov/stable-diffusion-portable?ysclid=ll12r244uq982835700) and all the extensions I have installed are working properly. This build is updated with the original version. FFMPEG and other dependencies are installed, paths are set. 

Screenshots of the error [THERE](https://disk.yandex.ru/d/rUtMwvf6D4E3Gg )

Is there any solution to this problem?

**Comment by numz** [comment]
Hi!

Really sorry about this error, can you tell me : 
- the python version use in your installer?
- the webui version? 

Thanks

**Comment by alexbofa** [comment]
Hello!
```bat
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
```

I fixed it like this, but I don't know if it's right, but it works.
I assume this is an error in the `appdirs`  module

I created a **.bat** with such data, before replacing `..\extensions\sd-wav2lip-uhq\requirements.txt` this [requirements.txt](https://github.com/numz/wav2lip_uhq/blob/main/requirements.txt)
```bat
set appdata=tmp
set userprofile=tmp
set temp=tmp
set path=git\cmd;python;venv\scripts
call venv\scripts\activate.bat
pip uninstall appdirs
```

**Comment by numz** [comment]
Thanks for your fix,

Appdirs is a depreciate package, i'm ok with the solution

I close this issue because it not due to sd-wav2lip-uhq

Thanks

**Comment by alexbofa** [comment]
Do you know why it can be created `appdirs`? I can't find an extension yet that creates this module from time to time.

**Comment by numz** [comment]
I think that came from your installer : 
[Installer](https://github.com/serpotapov/stable-diffusion-portable?ysclid=ll12r244uq982835700)
