### ISSUE TITLE
Progress in the console

### ISSUE THREAD

**Issue by alexbofa** [numz/sd-wav2lip-uhq#15]
Hello

I am currently making video+sound. 1080x1920
![image](https://github.com/numz/sd-wav2lip-uhq/assets/58225118/0b69f08e-27b4-4e53-8cb2-3836c7e80480)

But I don't see the process in the console, I only see that the video card's cuda is triggered. Somehow it is possible to display the process as when generating in automation, so that the process is visible. Since it is not clear how much more he has to do.

![Screen-1549](https://github.com/numz/sd-wav2lip-uhq/assets/58225118/2db2ccd9-5b08-4a38-b9e8-d8d5a7f71285)

Is it possible to make the progress bar not so big?
![Screen-1559](https://github.com/numz/sd-wav2lip-uhq/assets/58225118/6e25d432-6878-432d-a1f1-6a62970ab2d9)

**Comment by JustCann** [comment]
I have this issue as well, although for me the bar does not move or update.

**Comment by 1busyguy** [comment]
Same - 
Is there a limit on the length of the video used as the source?
Is there a limit on the size of that video or it's resolution?

![image](https://github.com/numz/sd-wav2lip-uhq/assets/807880/f9c813a0-ae81-493b-a165-5a0d990e793f)

**Comment by numz** [comment]
Hi, 

I've made an update and have taken into account your requests. Let me know if this is satisfactory?
@alexbofa 1080x1920 is probably too high, let me now if it finally works.

@1busyguy I don't believe there's a size limit; however, there is a maximum resolution limit. I'm not aware of this specific limit, but if the logs suggest using the "resize factor," then it means the image resolution is too high.

**Comment by numz** [comment]
I close this issue, let me know if you think we have to reopen it

Regards
