### ISSUE TITLE
Error loading script: wav2lip_uhq

### ISSUE THREAD

**Issue by DelaLlata** [numz/sd-wav2lip-uhq#17]
Can't make it work. Can you help me with this? ThankYou.

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.1
Commit hash: 68f336bd994bed5442ad95bad6b6ad5564a5409a
Installing wav2lip_uhq requirement: dlib-bin
Installing wav2lip_uhq requirement: opencv-python
Installing wav2lip_uhq requirement: pillow
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python

Launching Web UI with arguments: --autolaunch --xformers
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "C:\AI\SDXL\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\SDXL\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\SDXL\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 4, in <module>
        from scripts.wav2lip.wav2lip_uhq import Wav2LipUHQ
      File "C:\AI\SDXL\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\wav2lip_uhq.py", line 8, in <module>
        import dlib
      File "C:\AI\SDXL\system\python\lib\site-packages\dlib\__init__.py", line 19, in <module>
        from _dlib_pybind11 import *
    ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "C:\AI\SDXL\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\SDXL\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\SDXL\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 15, in <module>
        init_wav2lip_uhq()
      File "C:\AI\SDXL\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 9, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "C:\AI\SDXL\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 4, in <module>
        from scripts.wav2lip.wav2lip_uhq import Wav2LipUHQ
      File "C:\AI\SDXL\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\wav2lip_uhq.py", line 8, in <module>
        import dlib
      File "C:\AI\SDXL\system\python\lib\site-packages\dlib\__init__.py", line 19, in <module>
        from _dlib_pybind11 import *
    ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.

**Comment by numz** [comment]
Hi,
Sorry about this error.

Can you tell me more on your environnement :
Windows version?
did you have visual studio installed?
can you send me the "pip list" command of your stable diffusion env here, please?

**Comment by DelaLlata** [comment]
Thank you so much for the response!

Here is it:

Windows 10Pro v 22h2
Python 10.3.9
Microsoft Visual Studio Community 17.6.4

Pip List
Package                   Version
------------------------- ---------------
absl-py                   1.4.0
accelerate                0.18.0
addict                    2.4.0
aenum                     3.1.15
aiofiles                  23.2.1
aiohttp                   3.8.5
aiosignal                 1.3.1
altair                    5.0.1
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
appdirs                   1.4.4
async-timeout             4.0.3
attrs                     23.1.0
audioread                 3.0.0
basicsr                   1.4.2
beautifulsoup4            4.12.2
blendmodes                2022
boltons                   23.0.0
cachetools                5.3.1
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
clean-fid                 0.1.35
click                     8.1.6
clip                      1.0
colorama                  0.4.6
contourpy                 1.1.0
cycler                    0.11.0
decorator                 5.1.1
deprecation               2.1.0
dlib-bin                  19.24.2
einops                    0.4.1
exceptiongroup            1.1.2
facexlib                  0.3.0
fastapi                   0.94.0
ffmpy                     0.3.1
filelock                  3.12.2
filterpy                  1.4.5
fonttools                 4.42.0
frozenlist                1.4.0
fsspec                    2023.6.0
ftfy                      6.1.1
future                    0.18.3
gdown                     4.7.1
gfpgan                    1.3.8
gitdb                     4.0.10
GitPython                 3.1.30
google-auth               2.22.0
google-auth-oauthlib      1.0.0
gradio                    3.32.0
gradio_client             0.4.0
grpcio                    1.57.0
h11                       0.12.0
httpcore                  0.15.0
httpx                     0.24.1
huggingface-hub           0.16.4
idna                      3.4
imageio                   2.31.1
imageio-ffmpeg            0.4.8
importlib-metadata        6.8.0
imutils                   0.5.4
inflection                0.5.1
Jinja2                    3.1.2
joblib                    1.3.2
jsonmerge                 1.8.0
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
kiwisolver                1.4.4
kornia                    0.6.7
lark                      1.1.2
lazy_loader               0.3
librosa                   0.10.0.post2
lightning-utilities       0.9.0
linkify-it-py             2.0.2
llvmlite                  0.40.1
lmdb                      1.4.1
lpips                     0.1.4
Markdown                  3.4.4
markdown-it-py            2.2.0
MarkupSafe                2.1.3
matplotlib                3.7.2
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mpmath                    1.3.0
msgpack                   1.0.5
multidict                 6.0.4
networkx                  3.1
numba                     0.57.1
numpy                     1.23.5
oauthlib                  3.2.2
omegaconf                 2.2.3
open-clip-torch           2.20.0
opencv-contrib-python     4.8.0.76
opencv-python             4.8.0.76
orjson                    3.9.4
packaging                 23.1
pandas                    2.0.3
piexif                    1.1.3
Pillow                    9.5.0
pip                       22.3.1
platformdirs              3.10.0
pooch                     1.6.0
protobuf                  3.20.0
psutil                    5.9.5
pyasn1                    0.5.0
pyasn1-modules            0.3.0
pycparser                 2.21
pydantic                  1.10.12
pydub                     0.25.1
Pygments                  2.16.1
pyparsing                 3.0.9
PySocks                   1.7.1
python-dateutil           2.8.2
python-multipart          0.0.6
pytorch-lightning         1.9.4
pytz                      2023.3
PyWavelets                1.4.1
PyYAML                    6.0.1
realesrgan                0.3.0
referencing               0.30.2
regex                     2023.8.8
requests                  2.31.0
requests-oauthlib         1.3.1
resize-right              0.0.2
rpds-py                   0.9.2
rsa                       4.9
safetensors               0.3.1
scikit-image              0.20.0
scikit-learn              1.3.0
scipy                     1.11.1
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                65.5.0
six                       1.16.0
smmap                     5.0.0
sniffio                   1.3.0
soundfile                 0.12.1
soupsieve                 2.4.1
soxr                      0.3.5
starlette                 0.26.1
sympy                     1.12
tb-nightly                2.15.0a20230812
tensorboard-data-server   0.7.1
threadpoolctl             3.2.0
tifffile                  2023.7.18
timm                      0.6.7
tokenizers                0.13.3
tomesd                    0.1.2
tomli                     2.0.1
toolz                     0.12.0
torch                     2.0.1+cu118
torchdiffeq               0.2.3
torchmetrics              1.0.3
torchsde                  0.2.5
torchvision               0.15.2+cu118
tqdm                      4.66.1
trampoline                0.1.2
transformers              4.25.1
typing_extensions         4.7.1
tzdata                    2023.3
uc-micro-py               1.0.2
urllib3                   1.26.16
uvicorn                   0.23.2
wcwidth                   0.2.6
websockets                11.0.3
Werkzeug                  2.3.6
wheel                     0.41.1
yapf                      0.40.1
yarl                      1.9.2
zipp                      3.16.2

----------------------------------

Thank You!

**Comment by numz** [comment]
in your python venv can you : 
`pip uninstall dlib-bin`
`pip install dlib`

let me know 

Thanks

**Comment by DelaLlata** [comment]
No luck, same result. if you think I can do any thing else please let me know. I will love to try your fantastic work!
It will be nice to have a standalone app option (without Automatic1111).

Thank you for the time and effort!

**Comment by numz** [comment]
ok, let's try to reinstall dlib-bin?
`pip install dlib-bin`

i'll try to make a standalone one later :-)

**Comment by DelaLlata** [comment]
Still the same :( 
Any other idea?

ThankYou

**Comment by numz** [comment]
do you have CUDA installed?

**Comment by DelaLlata** [comment]
yes I do! vers 11.4

**Comment by numz** [comment]
please,can you try this please?
https://www.youtube.com/watch?v=3Vf_DEjUKkg

**Comment by DelaLlata** [comment]
I will! Thank You, I let you know

**Comment by DelaLlata** [comment]
Still doesn't work. I will try with a fresh windows install later.
Thank you for the incredible support and patience. 
Looking forward to use your stand alone app when it's ready.
Thank You Again.

**Comment by numz** [comment]
ok, thanks you for your patience too...
I'm really sorry for that issue, i see other dlib users have this issue but no one have a clear answer ....
I close it and i'll tell you when i make a standalone product

See yah!!
