### ISSUE TITLE
Transfer Lips from original Video to generated Vid

### ISSUE THREAD

**Issue by p0mad** [numz/sd-wav2lip-uhq#2]
Hi, 
My video is not English! and I've created a video using SD+CN using Img2img. (creating a video from existing Video)
So i was wondering if it is possible to use your great project to map the original Video Lips and face motions to the generated Video ( which lacks the accuracy on Lips and face motions)?

Thanks
Regards

**Comment by p0mad** [comment]
I dont need to use Audio!
Just map the lips and face motions between the two videos!

**Comment by numz** [comment]
Hi,

I'm sorry, but in its current state, the project does not support transferring the lip and face movements from an original video to a generated video. However, it's worth noting that Wav2Lip is designed to work with many languages, so if you have an audio source of the speech, it should work well. 

Nevertheless, this is an interesting idea and could be a feature to consider for future updates. Please send me one image from the original video and one from the generated video. I'll then see if I can easily update the project.

Thank you for your interest in our project!

**Comment by p0mad** [comment]
@numz 
May i have your Skype, Telegram, Email Address?
Best regards

**Comment by numz** [comment]
my discord : NumZ#7184

**Comment by p0mad** [comment]
@numz 
Send a request

**Comment by numz** [comment]
Ok, i have accepted, I close the issue :)
