### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Zakabaka** [numz/sd-wav2lip-uhq#21]
Hi there
I finale understand the issue with code errors so there should not be an interruptions in video/frames where there is no fase on the screen, so the face should always be on the screen to make it works.
So it works but did nothing.
I choose the video, cut out the audio and then insers that video and the same cut audio as an audio.
program perform the task for several hours and as a result now I have the same video with audio. No any animations no effects there were nothing. looks like and output of video converter where I just merge video and audio.
May me I did somethig wrong. I choose revanimated checkpoint and the rest as it was shown in 'code' page.

**Comment by numz** [comment]
Hi,
Contact me on discord NumZ#7184, i'll try to help you

**Comment by numz** [comment]
@Zakabaka Try setting the "resize factor" to 4. If it works, it indicates that your graphics card is working hard to get the task done. If 4 works, then try 3, followed by 2...

let me know

**Comment by numz** [comment]
Hi,

I'm closing this issue, certainly come from video resolution too high or video too long for gpu rtx2060
