### ISSUE TITLE
Menu not appear

### ISSUE THREAD

**Issue by golendercaria** [numz/sd-wav2lip-uhq#28]
Hello,

I installed automatic1111 and It wrk well. I follow instruction of installation but menu not appear. I try to reboot server and menu not appear.

Is there anything I can do to see if there is an error?

**Comment by numz** [comment]
Hye, sorry about that ,
Can you tell me more about installation?
Python version?
Did you use the 'sd.webui.zip', for installation?

**Comment by jacknoakes** [comment]
Yes, the bark integration is broken.  I just tried a clean install of SD webui 1.0-pre zip with all the updates to 1.5.2 in a completely separate folder and when trying to activate the extension with the bark update from a few days ago, I'm getting this console error:

`*** Error running install.py for extension D:\sd.webui-2\webui\extensions\sd-wav2lip-uhq.
*** Command: "D:\sd.webui-2\system\python\python.exe" "D:\sd.webui-2\webui\extensions\sd-wav2lip-uhq\install.py"
*** Error code: 1
*** stdout: Installing wav2lip_uhq requirement: dlib-bin
*** Installing wav2lip_uhq requirement: opencv-python
*** Installing wav2lip_uhq requirement: pillow
*** Installing wav2lip_uhq requirement: librosa==0.10.0.post2
*** Installing wav2lip_uhq requirement: opencv-contrib-python
*** Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
***
*** stderr: Traceback (most recent call last):
***   File "D:\sd.webui-2\webui\extensions\sd-wav2lip-uhq\install.py", line 10, in <module>
***     launch.run_pip(f"install {lib}", f"wav2lip_uhq requirement: {lib}")
***   File "D:\sd.webui-2\webui\modules\launch_utils.py", line 136, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\sd.webui-2\webui\modules\launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git.
*** Command: "D:\sd.webui-2\system\python\python.exe" -m pip install git+https://github.com/suno-ai/bark.git --prefer-binary
*** Error code: 2
*** stdout: Collecting git+https://github.com/suno-ai/bark.git
***   Cloning https://github.com/suno-ai/bark.git to c:\users\user\appdata\local\temp\pip-req-build-3328bzgg
***   Resolved https://github.com/suno-ai/bark.git to commit 95c9b43f20f6cede5dd4a36b8cfcc53e0cf53d39
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***
*** stderr:   Running command git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-3328bzgg'
*** ERROR: Exception:
*** Traceback (most recent call last):
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
***     status = run_func(*args)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
***     return func(self, options, args)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
***     requirement_set = resolver.resolve(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 73, in resolve
***     collected = self.factory.collect_root_requirements(root_reqs)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 491, in collect_root_requirements
***     req = self._make_requirement_from_install_req(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 453, in _make_requirement_from_install_req
***     cand = self._make_candidate_from_link(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
***     self._link_candidate_cache[link] = LinkCandidate(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
***     super().__init__(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
***     self.dist = self._prepare()
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
***     dist = self._prepare_distribution()
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
***     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
***     return self._prepare_linked_requirement(req, parallel_builds)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 653, in _prepare_linked_requirement
***     dist = _get_prepared_distribution(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 69, in _get_prepared_distribution
***     abstract_dist.prepare_distribution_metadata(
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 48, in prepare_distribution_metadata
***     self._install_build_reqs(finder)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 118, in _install_build_reqs
***     build_reqs = self._get_build_requires_wheel()
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 95, in _get_build_requires_wheel
***     return backend.get_requires_for_build_wheel()
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 697, in get_requires_for_build_wheel
***     return super().get_requires_for_build_wheel(config_settings=cs)
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
***     return self._call_hook('get_requires_for_build_wheel', {
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
***     raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
***   File "D:\sd.webui-2\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
***     obj = import_module(mod_path)
***   File "importlib\__init__.py", line 126, in import_module
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\Users\user\AppData\Local\Temp\pip-build-env-b7bzcumx\overlay\Lib\site-packages\setuptools\__init__.py", line 15, in <module>
***     import setuptools.version
***   File "C:\Users\user\AppData\Local\Temp\pip-build-env-b7bzcumx\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
***     from ._importlib import metadata
***   File "C:\Users\user\AppData\Local\Temp\pip-build-env-b7bzcumx\overlay\Lib\site-packages\setuptools\_importlib.py", line 45, in <module>
***     import importlib.metadata as metadata  # noqa: F401
***   File "importlib\metadata\__init__.py", line 17, in <module>
***   File "importlib\metadata\_adapters.py", line 3, in <module>
***   File "email\message.py", line 15, in <module>
***   File "email\utils.py", line 29, in <module>
***   File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
*`

**Comment by numz** [comment]
Hello
ok, thanks for report. I think that came from 3.10.6 python version and bark. For the moment i recommand to **not use sd.webui.zip.**. sorry about that

if you want, follow this :
- Install python 3.10.11
- Install ffmpeg
remove your stable diffusion folder
then :
`
cd D:\
git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
cd stable-diffusion-webui
python -m venv venv
`
- then edit file webui-user.bat and write this:

@echo off

set PYTHON="path to your python 3.10.11 python exe"  for me => c:\NUMZ\APPS\python-3.10\python.exe

set GIT=
set VENV_DIR=venv
set COMMANDLINE_ARGS=--xformers
call webui.bat


Let me know, if that works for you

Regards

**Comment by jacknoakes** [comment]
I'll try it in a secondary install, but on my main SD install (the zip one which has a lot of customizations that I can't just blow away), I just used your commit from before the bark integration and it works great.  I don't need bark at this stage, at least not the generic TTS voices - I'm looking at using the voice cloning support, and the repo for TTS Generation WebUI has a lot of features in it.  I need a replacement for ElevenLabs voice cloning.  I also need to be able to chop up video between the audio generation and wav2lip stages anyway, so the one-stop shop method won't work in my scenario.

**Comment by golendercaria** [comment]
It's possible to make install with specific commit or stable branche ? Previous from install of bark. Thank for community.

**Comment by golendercaria** [comment]
I clone repository on specific commit and It work : https://github.com/golendercaria/wav2lipStable.git

# Process on linux server
1) remove folder sd-wav2lip on stable-diffusion/extension
2) reboot/reload UI => the wav2lip need to be remove
3) follow initial instruction with link : https://github.com/golendercaria/wav2lipStable.git
4) reload UI 

For me i need to reload my server.

# Commit how work
```
commit 6967d1a4a782ba04a2a1068e3aeaec6d684c2f3b (HEAD -> master, origin/master)
Author: numz <numzzz@hotmail.com>
Date:   Sun Aug 6 19:15:54 2023 +0200

    update librosa version to 0.10.0
```

**Comment by genglinxiao** [comment]
Same here. I'm on an M2 Macbook. It seems to me the offending issue is the installing of dlib-bin. I always get this error:
> ERROR: Could not find a version that satisfies the requirement dlib-bin (from versions: none)
> ERROR: No matching distribution found for dlib-bin
I tried different methods but so far none of them worked.
It would be great if someone can share the proper way to install this module on an M2 MacBook.

**Comment by BTakacs-Oxit** [comment]
Probably the same issue as in https://github.com/numz/sd-wav2lip-uhq/issues/35  Chek the versions of WebUI

**Comment by numz** [comment]
@genglinxiao Hi sorry for that, on Mac you need dlib and not dlib-bin.
To resolve this issue, in the requirements.txt change "dlib-bin" to "dlib".
Let me know :)

**Comment by genglinxiao** [comment]
> @genglinxiao Hi sorry for that, on Mac you need dlib and not dlib-bin. To resolve this issue, in the requirements.txt change "dlib-bin" to "dlib". Let me know :)

Wow, I should have known. And indeed that fixed the issue. Thanks!
