### ISSUE TITLE
macbook m1 is extremly slow

### ISSUE THREAD

**Issue by shiyoudi2019** [numz/sd-wav2lip-uhq#32]
macbook m1 is using cpu to generate video, very slow

**Comment by numz** [comment]
Hi,

Do you know which step take time?
regards

**Comment by shiyoudi2019** [comment]
> Hi,
> 
> Do you know which step take time? regards

the step after OOM. 

<img width="1439" alt="image" src="https://github.com/numz/sd-wav2lip-uhq/assets/52911048/77dd8c1a-aec8-41f2-ba5b-543ba4fcac9e">

**Comment by shiyoudi2019** [comment]
M1 with 8GB memory Macbook

**Comment by numz** [comment]
Ok ,
Try "resize factor" by 2 for check if it speed up the process?

**Comment by numz** [comment]
Seems using too high resolution video file
