### ISSUE TITLE
Does not work offline/HD problem

### ISSUE THREAD

**Issue by cowboyab** [numz/sd-wav2lip-uhq#33]
Hi and thanks for great work. Thanks. 
I have two issues.
They may be similar to some earlier issues, but being novice, I'm unsure...

1. Files greater than 896x512, like 720 or1080  it does not seem to work. Gpu stuck at 100% 
What is the max video input resolution? I have a 2080 gpu
Tried installing the Nvidia specific A1111 installer, but it did not work, and I had to go with option 2

2. Every time i run A1111 it does this:
Installing wav2lip_uhq requirement: dlib-bin
Installing wav2lip_uhq requirement: opencv-python
Installing wav2lip_uhq requirement: pillow
Installing wav2lip_uhq requirement: librosa==0.10.0.post2
Installing wav2lip_uhq requirement: opencv-contrib-python
Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git

If I start without network I get:
venv "C:\Users\Boya PC\sd.webui\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.2
Commit hash: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c
*** Error running install.py for extension C:\Users\Boya PC\sd.webui\webui\extensions\sd-wav2lip-uhq.
*** Command: "C:\Users\Boya PC\sd.webui\webui\venv\Scripts\python.exe" "C:\Users\Boya PC\sd.webui\webui\extensions\sd-wav2lip-uhq\install.py"
*** Error code: 1
*** stdout: Installing wav2lip_uhq requirement: dlib-bin
*** Installing wav2lip_uhq requirement: opencv-python
*** Installing wav2lip_uhq requirement: pillow
*** Installing wav2lip_uhq requirement: librosa==0.10.0.post2
*** Installing wav2lip_uhq requirement: opencv-contrib-python
*** Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
***
*** stderr: Traceback (most recent call last):
***   File "C:\Users\Boya PC\sd.webui\webui\extensions\sd-wav2lip-uhq\install.py", line 10, in <module>
***     launch.run_pip(f"install {lib}", f"wav2lip_uhq requirement: {lib}")
***   File "C:\Users\Boya PC\sd.webui\webui\modules\launch_utils.py", line 136, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\Users\Boya PC\sd.webui\webui\modules\launch_utils.py", line 113, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git.
*** Command: "C:\Users\Boya PC\sd.webui\webui\venv\Scripts\python.exe" -m pip install git+https://github.com/suno-ai/bark.git --prefer-binary
*** Error code: 1
*** stdout: Collecting git+https://github.com/suno-ai/bark.git
***   Cloning https://github.com/suno-ai/bark.git to c:\users\boya pc\appdata\local\temp\pip-req-build-wo4lxrkr
***
*** stderr:   Running command git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\Boya PC\AppData\Local\Temp\pip-req-build-wo4lxrkr'
***   fatal: unable to access 'https://github.com/suno-ai/bark.git/': Could not resolve host: github.com
***   error: subprocess-exited-with-error
***
***   git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\Boya PC\AppData\Local\Temp\pip-req-build-wo4lxrkr' did not run successfully.
***   exit code: 128
***
***   See above for output.
***
***   note: This error originates from a subprocess, and is likely not a problem with pip.
*** error: subprocess-exited-with-error
***
*** git clone --filter=blob:none --quiet https://github.com/suno-ai/bark.git 'C:\Users\Boya PC\AppData\Local\Temp\pip-req-build-wo4lxrkr' did not run successfully.
*** exit code: 128
***
*** See above for output.
***
*** note: This error originates from a subprocess, and is likely not a problem with pip.
***
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Loading weights [6ce0161689] from C:\Users\Boya PC\sd.webui\webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
*** Error executing callback ui_tabs_callback for C:\Users\Boya PC\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py
    Traceback (most recent call last):
      File "C:\Users\Boya PC\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 68, in on_ui_tabs
        audio_example = gr.Audio(label="Audio example",
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\components.py", line 2390, in __init__
        IOComponent.__init__(
      File "C:\Users\Boya PC\sd.webui\webui\modules\scripts.py", line 654, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\components.py", line 215, in __init__
        else self.postprocess(initial_value)
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\components.py", line 2591, in postprocess
        file_path = self.make_temp_copy_if_needed(y)
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\components.py", line 259, in make_temp_copy_if_needed
        temp_dir = self.hash_file(file_path)
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\components.py", line 223, in hash_file
        with open(file_path, "rb") as f:
    OSError: [Errno 22] Invalid argument: 'https://dl.suno-models.io/bark/prompts/prompt_audio/en_speaker_0.mp3'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Boya PC\sd.webui\webui\modules\script_callbacks.py", line 153, in ui_tabs_callback
        res += c.callback() or []
      File "C:\Users\Boya PC\sd.webui\webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 37, in on_ui_tabs
        with gr.Blocks(analytics_enabled=False) as wav2lip_uhq_interface:
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1411, in __exit__
        self.config = self.get_config_file()
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\blocks.py", line 1378, in get_config_file
        props = block.get_config() if hasattr(block, "get_config") else {}
      File "C:\Users\Boya PC\sd.webui\webui\venv\lib\site-packages\gradio\components.py", line 2408, in get_config
        "value": self.value,
    AttributeError: 'Audio' object has no attribute 'value'

---
Creating model from config: C:\Users\Boya PC\sd.webui\webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 21.4s (launcher: 12.9s, import torch: 3.3s, import gradio: 0.8s, setup paths: 0.8s, other imports: 0.9s, load scripts: 1.6s, create ui: 0.4s, gradio launch: 0.5s, app_started_callback: 0.1s).
Applying attention optimization: Doggettx... done.
Model loaded in 3.9s (load weights from disk: 0.7s, create model: 0.4s, apply weights to model: 0.8s, apply half(): 0.7s, move model to device: 1.1s).

**Comment by numz** [comment]
Hello, 
Sorry about that,
1. A rtx2080 seems to be a little too slow to achieve the process, you can try to put the "resize factor" to 2 or 3 for check if it compute.
2. Yes it's True, you have to be online, I'll try to avoid this

regards
