### ISSUE TITLE
Close the Original Mouth Video Feature?

### ISSUE THREAD

**Issue by holycowdude** [numz/sd-wav2lip-uhq#34]
I'm trying to reuse a video of someone talking to make them say something else but when I process the video using Wav2Lip I can still see the original mouth talking between silence / gaps in the new audio

Is it possible to close the original mouth on a video before adding the new lip movements? 
Or is there something we could add to the text prompt to close the mouth as a 1st pass?

Thanks and keep up the good work! 👍

**Comment by numz** [comment]
Hi,

Yes you can try add increase "Mouth Mask Dilate" and " mask blur" for example "30/60"
let me know

**Comment by holycowdude** [comment]
Thanks, i've tried again with 30/60 settings but the mouth can still be seen open and moving when it should be closed between words... i'll keep trying different settings

**Comment by numz** [comment]
I'll update slider to 128px in futur update
