### ISSUE TITLE
still can't see the "Wav2Lip UHQ" menu

### ISSUE THREAD

**Issue by wangbochao** [numz/sd-wav2lip-uhq#35]
Already tried restarting Automatic1111.
still can't see the "Wav2Lip UHQ" menu

**Comment by numz** [comment]
Hi,
Let me see logs in cmd Windows
Did you use sd_webui.zip? Or other automatic1111 install method?

**Comment by BTakacs-Oxit** [comment]
I have just updated WebUI to the latest v1.6.0 and there is a ModuleNotFoundError: No module named 'bark.generation' . Perhaps you have the same problem, the Menu will not show up when you have an error like that
