### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by liuhedong** [numz/sd-wav2lip-uhq#36]
RuntimeError: Detected that PyTorch and TorchAudio were compiled with different CUDA versions. PyTorch has CUDA version 11.8 whereas TorchAudio has CUDA version 11.7. Please install the TorchAudio version that matches your PyTorch version.

**Comment by numz** [comment]
Hi, 
That came from your initial installation of torch package , torch is installed with cuda 11.8 and torchaudio with cuda 11.7
Just uninstall/reinstall torchaudio will resolve the issue 
Let me know
Regards

**Comment by RinLovesYou** [comment]
Hardly a solution... obviously the same thing still happens. i have even installed torch+cu117 and the same thing still happens.

**Comment by RinLovesYou** [comment]
I don't know what kind of sham this is, i've also tried installing the cu118 version of torchaudio...

**Comment by RinLovesYou** [comment]
it would help installing it all in automatic's venv [🤦](https://emojipedia.org/person-facepalming)

**Comment by numz** [comment]
yes but my extension doesn't install torch and torchaudio.
for resolve the issue, you have to change this in the "venv"
so activate your "automatic1111" venv and uninstall torchaudio and reinstall with the cuda version installed on your computer

venv\Scripts\activate
pip uninstall torchaudio torch 
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

let me know if it works
regards

**Comment by hanishkeloth** [comment]
The following installation command works for me:  `pip install torch==2.0.0+cu117 torchvision==0.15.1+cu117 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu117`
