### ISSUE TITLE
Use without UI

### ISSUE THREAD

**Issue by Qjizhi** [numz/sd-wav2lip-uhq#37]
Hi, 

Thanks for your great work, can you provide how to use it by command lines? Or do you have any related scripts?

**Comment by numz** [comment]
Hi,
No sorry, I prepare a standalone version and try to include api for dev
regards

**Comment by Qjizhi** [comment]
> Hi, No sorry, I prepare a standalone version and try to include api for dev regards

Thank you. I would appreciate it if you could let me know when you are finished with this work.

**Comment by annncc** [comment]
Me too, I would be equally grateful!
