### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg ...

### ISSUE THREAD

**Issue by RONNYKHALIL** [numz/sd-wav2lip-uhq#4]
HI. Thanks so much for implementing this in A1111. 

I'm running in Paperspace and confirmed FFmpeg -version: "ffmpeg version 4.2.7-0ubuntu0.1"

However I keep getting this error: 
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg -y -i /tmp/gradio/5aeb60fa9989b9e4f701c6358b152a2d62947b62/21028_Infiniti_WildWorld-AIRedux_071823_RK.wav -i /notebooks/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/temp/result.avi -strict -2 -q:v 1 /notebooks/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/results/result_voice.mp4'

Any idea if its an FFmpeg issue or something else?

Thanks

**Comment by numz** [comment]
Hi, 
Thank you for your report, I will check what's happening and come back very soon.

**Comment by numz** [comment]
Ok, 
I make an update, can you tell me if it's ok now?
regards

**Comment by RONNYKHALIL** [comment]
thanks for the quick tweak. after update and restart, now getting the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/dist-packages/imageio_ffmpeg/binaries/ffmpeg-linux64-v4.2.2 -y -i /tmp/gradio/2771514770b74d94923f5b4fa778799e52122785/21028_Infiniti_WildWorld-AIRedux_071823_RK_1.wav -i /notebooks/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/temp/result.avi -strict -2 -q:v 1 /notebooks/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/results/result_voice.mp4'

**Comment by numz** [comment]
What i see is ffmpeg exists, so one of the other files don't exist, can you tell me which one ?
in a command line :
ls /tmp/gradio/2771514770b74d94923f5b4fa778799e52122785/21028_Infiniti_WildWorld-AIRedux_071823_RK_1.wav
ls /notebooks/sd/stable-diffusion-webui/extensions/sd-wav2lip-uhq/scripts/wav2lip/temp/result.avi

thanks :)

**Comment by RONNYKHALIL** [comment]
result.avi isn't something I'm familiar with, I don't work with avi's

**Comment by numz** [comment]
i make another update, can you update et restart please?

Let me know :)

**Comment by RONNYKHALIL** [comment]
that did the trick! thank you!

**Comment by numz** [comment]
cooool :)

Thank you !!!!!!
