### ISSUE TITLE
Availability thru A1111 API

### ISSUE THREAD

**Issue by sjc57** [numz/sd-wav2lip-uhq#40]
A1111 can be started with the --api option - the docs are available on http://127.0.0.1:7860/docs
I see, for example, /sdapi/v1/txt2img to access the txt2img functionality. Is there a way to access Wav2lip Studio in a similar fashion? Thanks

**Comment by annncc** [comment]
I also have the same requirement, and I've been researching it recently. If any experts have this plan, I would be extremely grateful!
