### ISSUE TITLE
process does not move

### ISSUE THREAD

**Issue by TheZandy** [numz/sd-wav2lip-uhq#48]
The process does not move when click generate

![image](https://github.com/numz/sd-wav2lip-uhq/assets/54242954/cdb3b231-2463-4543-a99f-71ebce452c64)

**Comment by Titukas22** [comment]
i have same issue how you solve it?

**Comment by edenweb1** [comment]
same problem here

**Comment by numz** [comment]
Often,  that came from the video resolution, try to keep resolution under 1000x1000px by using "resize factor"
