### ISSUE TITLE
How can I solve this problem? 

### ISSUE THREAD

**Issue by imdaewoong** [numz/sd-wav2lip-uhq#49]
*** Error loading script: ui.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: wav2lip_uhq.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 11, in <module>
        init_wav2lip_uhq()
      File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip_uhq.py", line 7, in init_wav2lip_uhq
        from ui import on_ui_tabs
      File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\ui.py", line 8, in <module>
        from scripts.faceswap.swap import FaceSwap
      File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---

**Comment by numz** [comment]
Hi
Can you tell me what is your python version? Webui version? And can you send me the webui start logs please?

**Comment by imdaewoong** [comment]
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20

**Comment by imdaewoong** [comment]
Already up to date.
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements
current transparent-background 1.2.4
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
C:\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq.
*** Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\install.py"
*** Error code: 1
*** stdout: Installing wav2lip_uhq requirement: dlib-bin
*** Installing wav2lip_uhq requirement: opencv-python
*** Installing wav2lip_uhq requirement: pillow
*** Installing wav2lip_uhq requirement: librosa==0.10.0.post2
*** Installing wav2lip_uhq requirement: opencv-contrib-python
*** Installing wav2lip_uhq requirement: git+https://github.com/suno-ai/bark.git
*** Installing wav2lip_uhq requirement: insightface==0.7.3
***
*** stderr: Traceback (most recent call last):
***   File "C:\stable-diffusion-webui\extensions\sd-wav2lip-uhq\install.py", line 10, in <module>
***     launch.run_pip(f"install {lib}", f"wav2lip_uhq requirement: {lib}")
***   File "C:\stable-diffusion-webui\modules\launch_utils.py", line 138, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install wav2lip_uhq requirement: insightface==0.7.3.
*** Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install insightface==0.7.3 --prefer-binary
*** Error code: 1
*** stdout: Collecting insightface==0.7.3
***   Using cached insightface-0.7.3.tar.gz (439 kB)
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***   Installing backend dependencies: started
***   Installing backend dependencies: finished with status 'done'
***   Preparing metadata (pyproject.toml): started
***   Preparing metadata (pyproject.toml): finished with status 'done'
*** Requirement already satisfied: numpy in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.23.5)
*** Collecting onnx (from insightface==0.7.3)
***   Obtaining dependency information for onnx from https://files.pythonhosted.org/packages/00/36/e7a7e7a85564e7d409e4e8addfa11d41015d2190bfff30064771e7c21ca0/onnx-1.14.1-cp310-cp310-win_amd64.whl.metadata
***   Using cached onnx-1.14.1-cp310-cp310-win_amd64.whl.metadata (15 kB)
*** Requirement already satisfied: tqdm in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (4.65.0)
*** Requirement already satisfied: requests in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
*** Requirement already satisfied: matplotlib in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.7.1)
*** Requirement already satisfied: Pillow in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
*** Requirement already satisfied: scipy in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.10.1)
*** Requirement already satisfied: scikit-learn in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.3.0)
*** Requirement already satisfied: scikit-image in c:\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
*** Collecting easydict (from insightface==0.7.3)
***   Using cached easydict-1.10-py3-none-any.whl
*** Collecting cython (from insightface==0.7.3)
***   Obtaining dependency information for cython from https://files.pythonhosted.org/packages/db/3e/8cf60af86446b129e79adee5d9131ec7eb043297e20c04bc31670331325c/Cython-3.0.2-cp310-cp310-win_amd64.whl.metadata
***   Using cached Cython-3.0.2-cp310-cp310-win_amd64.whl.metadata (3.2 kB)
*** Collecting albumentations (from insightface==0.7.3)
***   Obtaining dependency information for albumentations from https://files.pythonhosted.org/packages/9b/f6/c486cedb4f75147232f32ec4c97026714cfef7c7e247a1f0427bc5489f66/albumentations-1.3.1-py3-none-any.whl.metadata
***   Using cached albumentations-1.3.1-py3-none-any.whl.metadata (34 kB)
*** Collecting prettytable (from insightface==0.7.3)
***   Obtaining dependency information for prettytable from https://files.pythonhosted.org/packages/4d/81/316b6a55a0d1f327d04cc7b0ba9d04058cb62de6c3a4d4b0df280cbe3b0b/prettytable-3.9.0-py3-none-any.whl.metadata
***   Using cached prettytable-3.9.0-py3-none-any.whl.metadata (26 kB)
*** Requirement already satisfied: PyYAML in c:\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0)
*** Collecting qudida>=0.0.4 (from albumentations->insightface==0.7.3)
***   Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
*** Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.8.0.74)
*** Requirement already satisfied: networkx>=2.8 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.1)
*** Requirement already satisfied: imageio>=2.27 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.31.1)
*** Requirement already satisfied: tifffile>=2022.8.12 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2023.4.12)
*** Requirement already satisfied: PyWavelets>=1.1.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.4.1)
*** Requirement already satisfied: packaging>=21 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (23.1)
*** Requirement already satisfied: lazy_loader>=0.2 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.2)
*** Requirement already satisfied: contourpy>=1.0.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.1.0)
*** Requirement already satisfied: cycler>=0.10 in c:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.11.0)
*** Requirement already satisfied: fonttools>=4.22.0 in c:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.40.0)
*** Requirement already satisfied: kiwisolver>=1.0.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.4)
*** Requirement already satisfied: pyparsing>=2.3.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.0)
*** Requirement already satisfied: python-dateutil>=2.7 in c:\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
*** Collecting protobuf>=3.20.2 (from onnx->insightface==0.7.3)
***   Obtaining dependency information for protobuf>=3.20.2 from https://files.pythonhosted.org/packages/5e/46/5b9674a33cbf690ffdd79ab1863767a66461cd06ea7aeb9f90e4e50be7a5/protobuf-4.24.3-cp310-abi3-win_amd64.whl.metadata
***   Using cached protobuf-4.24.3-cp310-abi3-win_amd64.whl.metadata (540 bytes)
*** Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from onnx->insightface==0.7.3) (4.6.3)
*** Requirement already satisfied: wcwidth in c:\stable-diffusion-webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.6)
*** Requirement already satisfied: charset-normalizer<4,>=2 in c:\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.1.0)
*** Requirement already satisfied: idna<4,>=2.5 in c:\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.4)
*** Requirement already satisfied: urllib3<3,>=1.21.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (1.26.16)
*** Requirement already satisfied: certifi>=2017.4.17 in c:\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2023.5.7)
*** Requirement already satisfied: joblib>=1.1.1 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.3.2)
*** Requirement already satisfied: threadpoolctl>=2.0.0 in c:\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.2.0)
*** Requirement already satisfied: colorama in c:\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
*** Requirement already satisfied: six>=1.5 in c:\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
*** Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
*** Using cached Cython-3.0.2-cp310-cp310-win_amd64.whl (2.8 MB)
*** Using cached onnx-1.14.1-cp310-cp310-win_amd64.whl (13.3 MB)
*** Using cached prettytable-3.9.0-py3-none-any.whl (27 kB)
*** Using cached protobuf-4.24.3-cp310-abi3-win_amd64.whl (430 kB)
*** Building wheels for collected packages: insightface
***   Building wheel for insightface (pyproject.toml): started
***   Building wheel for insightface (pyproject.toml): finished with status 'error'
*** Failed to build insightface
***
*** stderr: WARNING: Ignoring invalid distribution -illow (c:\stable-diffusion-webui\venv\lib\site-packages)
*** WARNING: Ignoring invalid distribution -ransformers (c:\stable-diffusion-webui\venv\lib\site-packages)
***   error: subprocess-exited-with-error
***
***   Building wheel for insightface (pyproject.toml) did not run successfully.
***   exit code: 1
***
***   [214 lines of output]
***   WARNING: pandoc not enabled
***   running bdist_wheel
***   running build
***   running build_py
***   creating build
***   creating build\lib.win-amd64-cpython-310
***   creating build\lib.win-amd64-cpython-310\insightface
***   copying insightface\__init__.py -> build\lib.win-amd64-cpython-310\insightface
***   creating build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\common.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\face_analysis.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\mask_renderer.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\__init__.py -> build\lib.win-amd64-cpython-310\insightface\app
***   creating build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\insightface_cli.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\model_download.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\rec_add_mask_param.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\__init__.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   creating build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\image.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\pickle_object.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\rec_builder.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\__init__.py -> build\lib.win-amd64-cpython-310\insightface\data
***   creating build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\arcface_onnx.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\attribute.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\inswapper.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\landmark.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\model_store.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\scrfd.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\__init__.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty
***   copying insightface\thirdparty\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty
***   creating build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\constant.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\download.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\face_align.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\filesystem.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\storage.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\transform.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\__init__.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
***   copying insightface\thirdparty\face3d\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\fit.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\load.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\morphabel_model.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   running egg_info
***   writing insightface.egg-info\PKG-INFO
***   writing dependency_links to insightface.egg-info\dependency_links.txt
***   writing entry points to insightface.egg-info\entry_points.txt
***   writing requirements to insightface.egg-info\requires.txt
***   writing top-level names to insightface.egg-info\top_level.txt
***   reading manifest file 'insightface.egg-info\SOURCES.txt'
***   writing manifest file 'insightface.egg-info\SOURCES.txt'
***   C:\Users\mumuy\AppData\Local\Temp\pip-build-env-n0jria5e\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
***           already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   C:\Users\mumuy\AppData\Local\Temp\pip-build-env-n0jria5e\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.data.images' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.data.images' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.data.images' to be distributed and are
***           already explicitly excluding 'insightface.data.images' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   C:\Users\mumuy\AppData\Local\Temp\pip-build-env-n0jria5e\overlay\Lib\site-packages\setuptools\command\build_py.py:204: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.data.objects' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.data.objects' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.data.objects' to be distributed and are
***           already explicitly excluding 'insightface.data.objects' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   creating build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   creating build\lib.win-amd64-cpython-310\insightface\data\objects
***   copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   running build_ext
***   building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
***   error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
***   [end of output]
***
***   note: This error originates from a subprocess, and is likely not a problem with pip.
***   ERROR: Failed building wheel for insightface
*** ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
***
If submitting an issue on github, please provide the full startup log for debugging purposes.

**Comment by imdaewoong** [comment]
How can I solve this problem? please help me~!!

**Comment by imdaewoong** [comment]
Can you send me the previous version as a zip file?  imdaewoong@daum.net

**Comment by Blizaine** [comment]
I have the exact same two errors shown by OP at the start of the thread.  

Last time I used it was 5 days ago, which was before the recent commits 3 days ago.  I noticed that faceswap was added, so I added 'inswapper_128.onnx' to the faceswap/model folder, hoping that was related to the problem. But it didn't resolve.  I also disabled the wav2lip ext, removed the dir from extensions folder,  installed it fresh, and put all model weights back in their respective locations.   Issue persists.

**Comment by Blizaine** [comment]
I fixed my issue. Not sure if this will help.  I had both Python 3.10.6 and 3.11.x installed.  There was a path in my environment variables still pointing to 3.11 and it was higher than 3.10.6.  I removed that, and confirmed the path for 3.10.6 was correct (and moved it up the list), then rebooted.  I then removed the venv folder in the SDWebUI directory.  This forced a Python re-install when I launched the webui-user.bat.  Now Wav2Lip shows up as a tab tab again and appears to be working.

**Comment by numz** [comment]
Thanks @Blizaine 😊i hope it will help others

@imdaewoong Let me know if the blizaine fix works for you please

**Comment by imdaewoong** [comment]
thanks @Blizaine  and @numz

**Comment by numz** [comment]
@imdaewoong does it works?

**Comment by imdaewoong** [comment]
I am not a programmer. I am a composer and produce music. So I don't know exactly, but I slowly read your advice and content based on my experience studying a long time ago and finally solved the problem.
I'm trying to use AI to create a video to use for music.
I wish the mouth looked a little bigger to match the sound. When you open your mouth, the shape of your teeth is unnatural. I wish it looked a little more natural.
https://youtu.be/6MQvuCt9RgQ

**Comment by numz** [comment]
Thanks , so I close this issue
Regards
