### ISSUE TITLE
How about to implement HDTR Net?

### ISSUE THREAD

**Issue by rebotnix** [numz/sd-wav2lip-uhq#50]
I found HDTR Net intereseting, tested it on CMD line, and seems to produce good results.
https://github.com/yylgoodlucky/HDTR-Net

Maybe it´s an good alternate for the mouth restauration.

What do you think @numz ?

**Comment by numz** [comment]
Hi
Is that only for teeth restoration?than mean I could Apply this after the wav2lip process? Right?

**Comment by rebotnix** [comment]
@numz , yes, please take a look, it´s not bad for a mouth restauration. It also segments the region as far as i have seen. So after that we can merge it to the original video as you did with the restauration last part to keep the resolution. 

Demo:
![Bildschirmfoto 2023-09-17 um 22 52 30](https://github.com/numz/sd-wav2lip-uhq/assets/566761/e76a37e2-a7ba-4760-bb44-a5f87cd2ce58)
