### ISSUE TITLE
wav2lip  encountered a problem

### ISSUE THREAD

**Issue by argoo99** [numz/sd-wav2lip-uhq#59]
Right here, motionless，
Still the same after waiting for several hours
 python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  

set det-size: (640, 640)
Reading video frames for face swap...
Using cuda for inference.176 of 176 -
Reading video frames...
Number of frames available for inference: 176
(80, 481)
Length of mel chunks: 176
  0%|                                                                                            | 0/2 [00:00<?, ?it/s]
  0%|

**Comment by numz** [comment]
Hi,
usually due to image size, try to use "resize factor" 2 or 3, try to keep size under 1000x1000 px for speed up process and upscale in post process

**Comment by argoo99** [comment]
> Hi, usually due to image size, try to use "resize factor" 2 or 3, try to keep size under 1000x1000 px for speed up process and upscale in post process. Let me know regards

It has been solved. I worked on it all night yesterday. Thank you.
