### ISSUE TITLE
'insightface'

### ISSUE THREAD

**Issue by gebijiaxiaoming** [numz/sd-wav2lip-uhq#60]
building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
***       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
***       [end of output]
***   
***   note: This error originates from a subprocess, and is likely not a problem with pip.
***   ERROR: Failed building wheel for insightface
*** ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

     File "F:\aipeiyin\sd-\sd-A\sd-webui-aki-directml-v4.4\extensions\sd-wav2lip-uhq\scripts\faceswap\swap.py", line 6, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---

**Comment by numz** [comment]
Hi,
Thanks for report
Yes, you need to install  Microsoft Visual C++ 14.0 from https://visualstudio.microsoft.com/visual-cpp-build-tools/
I'll add it in README.md

Let me know if it works after install it

regards

**Comment by numz** [comment]
Thanks for report
Regards
