### ISSUE TITLE
several code errors

### ISSUE THREAD

**Issue by Zakabaka** [numz/sd-wav2lip-uhq#8]
![Screenshot 2023-08-05 105922](https://github.com/numz/sd-wav2lip-uhq/assets/83984191/6fcdd7b6-bc92-4326-bf8c-f494033433af)

Could you please explain what happening, looks like some errors in the code.
ffmpeg was installed (but it would be great if the would be a more detailed instruction how to do that to save time for users/ anyway) 
ffmpeg installed and seen in cmd. extension installed but there still errors.

**Comment by numz** [comment]
Hi,
This error seems to indicate that no face was detected in one of the images. Does that sound possible in your situation?

**Comment by Zakabaka** [comment]
Hello
I think not cause the vidie is good quality and all clear seen there.
Ill try to with other video ald reply here a bit later.

**Comment by Zakabaka** [comment]
![Screenshot2](https://github.com/numz/sd-wav2lip-uhq/assets/83984191/63da1cdf-dbb9-4483-af66-6ba18cb35cc2)


Same story. the soft starts workin but at some point it just give an error.
The video was clear.
Also just to make it clear. Any video can be added? video shoul be without audio? I meen as the audio shoul be added separately does it means that the video shhoul be without audio? 
Also coul it be because of ffmpeg? I installed it but not sure is it there I mean how  to check it? How ever the errors are not about the ffmpeg so it means that the problem is not about ffmpeg
Any way errors are still there.

**Comment by numz** [comment]
thanks for report, 
your last error is "face not detect..." that mean there is an image in the video sequence where face  too poor quality  or bad angle, or ...
you can find the bad image in : 
"c:\Users\user\stable-diffusion-webui\extensions\sd-wav2lip-uhq\scripts\wav2lip\temp\faulty_frame.jpg"
