### ISSUE TITLE
 fatal: unable to access 'https://github.com/numz/sd-wav2lip-uhq/': Recv failure: Connection was reset '

### ISSUE THREAD

**Issue by Pancat007** [numz/sd-wav2lip-uhq#83]
github代理开不开好像都连不上。。
一直下载失败。。。

**Comment by Pancat007** [comment]
用的秋叶启动器，在启动器里配代理就可以了。
新的问题是安装了，设置里显示有，但是实际上tab没有
![image](https://github.com/numz/sd-wav2lip-uhq/assets/32253420/03f95160-9ee7-4ea6-b653-6b2f876b37ba)
![image](https://github.com/numz/sd-wav2lip-uhq/assets/32253420/6f105a00-1c07-4e44-923a-6f66a29b84ad)

**Comment by vantang** [comment]
![image](https://github.com/numz/sd-wav2lip-uhq/assets/16954599/957d154a-9438-458c-a438-f969a74546c6)

**Comment by vantang** [comment]
用秋叶启动器的，这里要这么干
