### ISSUE TITLE
RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source.

### ISSUE THREAD

**Issue by ABZig** [numz/sd-wav2lip-uhq#84]
I am getting a Runtime error while running the web UI using ./webui.sh. Error is like,

**RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, if not please reinstall torchvision so that it matches your PyTorch install.**

I have tried many solutions to run it Errorlessly. But in the end, I was stuck in this error.
Tried Solutions,
- Downgrade Python version - 3.10/3.8
- Check & provide compatible versions of pytorch and torchvision
- Tried to upload different video, audio, and images -  if in case of issue with any corrupted media
- Tried with bark audio -  in case issue with uploaded audio, it might run with bark audio.
- Used Resize factor Slider as well

**Comment by Hank512** [comment]
me too

**Comment by ABZig** [comment]
During the run time of build.sh file it is taking the default version from the system. You need to set your version to 3.10 at least.
You can install pyenv in Ubuntu and follow the correct steps to install version 3.1o and set it globally. So, that build takes the latest version (https://stackoverflow.com/questions/62898911/how-to-downgrade-python-version-from-3-8-to-3-7-mac).
