### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Tobe2d** [numz/sd-wav2lip-uhq#9]
This is really cool and I would like to request some kind of control for the lip-sync.

For example, the way the lips are moving should be based on some parameters and based on audio frequency (+Increase or -Decrease)
Or something that can help control the amount of movments to the lips.

**Comment by numz** [comment]
Hi,

Thanks for your request :-)
I'll try to find a way to control this and i'll add more control on all hidden paramters 
 i'll close this post because it's not an issue but I will think about it :)

Regards

**Comment by Tobe2d** [comment]
Yes please do that.

How can I contact you directly?

**Comment by numz** [comment]
NumZ#7184 on discord
